export interface SkillSet {
    skillSword: number,
    skillClub: number,
    skillHammer: number,
    skillAxe: number,
    skillSpear: number,
    skillStaff: number,
    skillPolearm: number,
    skillBow: number,
    skillCriticalStrike: number,
    skillSpellcasting: number,
    skillDualWield: number,
    skillShield: number,
    skillAttackMagic: number,
    skillDefenseMagic: number,
    skillCharmMagic: number,
}

export const SkillSetKeys: (keyof SkillSet)[] = [
    "skillSword",
    "skillClub",
    "skillHammer",
    "skillAxe",
    "skillSpear",
    "skillStaff",
    "skillPolearm",
    "skillBow",
    "skillCriticalStrike",
    "skillSpellcasting",
    "skillDualWield",
    "skillShield",
    "skillAttackMagic",
    "skillDefenseMagic",
    "skillCharmMagic",
];
